# core/schemas/__init__.py

# Set the version for your data contracts.
# This allows you to track changes to the schemas themselves.
__version__ = "1.2.0"

# Import the core models to the top level of the package.
# This allows other developers to write `from core.schemas import TaskMessage`
# instead of the longer `from core.schemas.contracts import TaskMessage`.
from .contracts import (
    TaskPriority,
    TaskStatus,
    EntityType,
    AgentType,
    WorkerType,
    CostMetrics,
    AnalysisMetadata,
    DistilledDataset,
    ReflectionInsights,
    TaskMessage,
    ResultMessage,
)
from .specifications import (
    SpecificationLevel,
    SpecificationState,
    SpecificationDocument,
    L1Specification,
    ClockPolarity,
    ClockingInfo,
    ResetPolarity,
    SignalDirection,
    SignalDefinition,
    HandshakeProtocol,
    ConfigurationParameter,
    L2Specification,
    VerificationScenario,
    CoverageTarget,
    ResetConstraint,
    L3Specification,
    BlockDiagramNode,
    DependencyEdge,
    ConnectionEndpoint,
    Connection,
    ClockDomain,
    AssertionPlan,
    L4Specification,
    ArtifactRequirement,
    AcceptanceMetric,
    L5Specification,
    FrozenSpecification,
)

__all__ = [
    "__version__",
    "TaskPriority",
    "TaskStatus",
    "EntityType",
    "AgentType",
    "WorkerType",
    "CostMetrics",
    "AnalysisMetadata",
    "DistilledDataset",
    "ReflectionInsights",
    "TaskMessage",
    "ResultMessage",
    "SpecificationLevel",
    "SpecificationState",
    "SpecificationDocument",
    "L1Specification",
    "ClockPolarity",
    "ClockingInfo",
    "ResetPolarity",
    "SignalDirection",
    "SignalDefinition",
    "HandshakeProtocol",
    "ConfigurationParameter",
    "L2Specification",
    "VerificationScenario",
    "CoverageTarget",
    "ResetConstraint",
    "L3Specification",
    "BlockDiagramNode",
    "DependencyEdge",
    "ConnectionEndpoint",
    "Connection",
    "ClockDomain",
    "AssertionPlan",
    "L4Specification",
    "ArtifactRequirement",
    "AcceptanceMetric",
    "L5Specification",
    "FrozenSpecification",
]
